[default]
workshop = [
    "3499977893", # ADT
    "450814997", # CBA
    "463939057", # ACE3

    "3333302397", # JCA Weapons
    "3473383676", # JCA Equipment
    # "3661907264", # JCA CERA
]

[zen]
extends = "default"
workshop = [
    "1779063631", # Zeus Enhanced
]

[ws]
extends = "default"
dlc = [
    "ws",
]

[rf]
extends = "default"
dlc = [
    "rf",
]

[ef]
extends = "default"
dlc = [
    "ef",
]

[aegis]
extends = "ws"
workshop = [
    "2538332070", # Aegis - Development
]

[atlas]
extends = "default"
workshop = [
    "2538339575", # Atlas - Development
]

[uriki]
extends = "default"
workshop = [
    "synixe:@urikimissionitems"
]
