[default]
workshop = [
    "3499977893", # ADT
    "450814997", # CBA
    "463939057", # ACE3
]

[zen]
extends = "default"
workshop = [
    "1779063631", # Zeus Enhanced
]

[ws]
extends = "default"
dlc = [
    "ws",
]

[rf]
extends = "default"
dlc = [
    "rf",
]

[ef]
extends = "default"
dlc = [
    "ef",
]

[aegis]
extends = "ws"
workshop = [
    "2538332070", # Aegis - Development
]

[atlas]
extends = "default"
workshop = [
    "2538339575", # Atlas - Development
]

[jca_mp5a5]
extends = "default"
workshop = [
    "3302425224" # JCA MP5A5
]

[jca_ump45]
extends = "default"
workshop = [
    "3397288027" # JCA UMP45
]

[uriki]
extends = "default"
workshop = [
    "synixe:@urikimissionitems"
]
