name = "Synixe Armoury"
prefix = "synixe_armoury"
mainprefix = "s"
author = "Synixe Contractors & Theseus Incorporated"

[files]
include = [
    "mod.cpp",
    "README.md",
    "synixe_armoury_ca.paa"
]

[version]
git_hash = 0

[hemtt.release]
folder = "synixe_armoury"
